spring:
  datasource:
    url: jdbc:mysql://localhost:3306/KIRIN_RESERVE
    username: KIRIN_PROD
    password: ${MYSQL_PASSWORD}

server:
  port: ${APP_PORT}

line:
  bot:
    channel-token: ${LINE_BOT_CHANNEL_TOKEN}
    channel-secret: ${LINE_BOT_CHANNEL_SECRET}
    group-id: ${LINE_BOT_GROUP_ID}

kirin:
  user: ${KIRIN_USER}
  password: ${KIRIN_PASSWORD}
  url: ${KIRIN_URL}
  detail-url: ${KIRIN_RESERVATION_DETAIL_URL}
  interview-url: ${KIRIN_INTERVIEW_URL}
  start-time:
    am: ${KIRIN_START_TIME_AM}
    pm: ${KIRIN_START_TIME_PM}
  target-name: ${KIRIN_TARGET_NAME}
  target-id: ${KIRIN_TARGET_ID}

selenium:
  host: ${SELENIUM_HOST}

logging:
  file:
    name: ${LOG_PATH}

cron: ${CRON}
